insert into item_types values(GETDATE(),null,'N//A')
insert into item_types values(GETDATE(),null,'Laptop')
insert into item_types values(GETDATE(),null,'Desktop')
insert into item_types values(GETDATE(),null,'Mobile')
insert into item_types values(GETDATE(),null,'Tablet')

insert into permissions values(GETDATE(),NULL,'Create')
insert into permissions values(GETDATE(),NULL,'Update')
insert into permissions values(GETDATE(),NULL,'Delete')
insert into permissions values(GETDATE(),NULL,'View')
insert into permissions values(GETDATE(),NULL,'Import')
insert into permissions values(GETDATE(),NULL,'Export')

insert into platform values(GETDATE(),NULL,'N//A','N//A')
insert into platform values(GETDATE(),NULL,'Android','7.5')
insert into platform values(GETDATE(),NULL,'Android','13.2')
insert into platform values(GETDATE(),NULL,'Android','11.1')
insert into platform values(GETDATE(),NULL,'Android','10.1')
insert into platform values(GETDATE(),NULL,'Android','10.2')
insert into platform values(GETDATE(),NULL,'iOs','10')
insert into platform values(GETDATE(),NULL,'iOs','8.2')
insert into platform values(GETDATE(),NULL,'iOs','12.1')
insert into platform values(GETDATE(),NULL,'iOs','15.1')

insert into rams values(GETDATE(),NULL,3)
insert into rams values(GETDATE(),NULL,4)
insert into rams values(GETDATE(),NULL,16)
insert into rams values(GETDATE(),NULL,32)
insert into rams values(GETDATE(),NULL,8)
insert into rams values(GETDATE(),NULL,64)
insert into rams values(GETDATE(),NULL,128)
insert into rams values(GETDATE(),NULL,256)

insert into storages values(GETDATE(),NULL,164)
insert into storages values(GETDATE(),NULL,256)
insert into storages values(GETDATE(),NULL,300)
insert into storages values(GETDATE(),NULL,512)
insert into storages values(GETDATE(),NULL,128)
insert into storages values(GETDATE(),NULL,1024)


insert into screens values(GETDATE(),NULL,17)
insert into screens values(GETDATE(),NULL,13)
insert into screens values(GETDATE(),NULL,14)
insert into screens values(GETDATE(),NULL,12)
insert into screens values(GETDATE(),NULL,16)
insert into screens values(GETDATE(),NULL,18)
insert into screens values(GETDATE(),NULL,20)

