ALTER TABLE users DROP COLUMN verification_code;

ALTER TABLE users MODIFY email VARCHAR(50) NOT NULL;

ALTER TABLE users MODIFY enabled BIT(1) NOT NULL;

ALTER TABLE users MODIFY first_name VARCHAR(20) NOT NULL;

ALTER TABLE users MODIFY last_name VARCHAR(20) NOT NULL;

ALTER TABLE system_roles MODIFY name VARCHAR(20) NOT NULL;

ALTER TABLE users MODIFY user_name VARCHAR(20) NOT NULL;