ALTER TABLE rams DROP COLUMN size;

ALTER TABLE rams ADD size VARCHAR(255) NOT NULL;

ALTER TABLE screens DROP COLUMN size;

ALTER TABLE screens ADD size VARCHAR(255) NOT NULL;

ALTER TABLE storages DROP COLUMN size;

ALTER TABLE storages ADD size VARCHAR(255) NOT NULL;